apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items-service
  template:
    metadata:
      labels:
        app: items-service
    spec:
      containers:
      - name: items-service
        image: loannguyent5/items-service
        ports:
        - containerPort: 5000
